### ISSUE TITLE
NuGet package bundles Newtonsoft.Json.dll

### ISSUE THREAD

**Issue by roryprimrose** [danielcrenna/tweetsharp#179]
Hi guys,

The TweetSharp nuget package is bundling newtonsoft.json.dll as well has having it has a package dependency. Having the binary in the package is causing compilation failures as other packages are not compatible with the one provided in your package.

**Comment by DaveGreasley** [comment]
Can I second how much of a seriously annoying issue this is! Should only have the package dependency.

**Comment by Yortw** [comment]
Hi,

As mentioned in the readme file, this repo is now abandoned. It is not being maintained, do not expect any updates. Not only is the repo dead, but the original author has lost the associated nuget account details so the package is unlikely to be updated/withdrawn from Nuget either. You should also be aware the nuget package is unreliable. It contains code older than currently exists in the repo, and that doesn't work well with Twitter changes since 2013. In particular it fails when it encounters long/big user ids, which are becoming more and more frequent.

Your options are;

1. Download the code and get it building yourself. This isn't rocket science, but it doesn't just work either. Some effort is required to get TweetSharp and Hammock all lined up correctly and be able to build for all the different supported platforms. Doing this should resolve your json.net reference issue, and also give you some of the newer code with support for long user ids.

2. Use one of the TweetSharp forks published via Nuget. I know TweetMoaSharp fixes the Json.net reference you mention. There is also TweetSharp-Unofficlal and TweetSharp-Windows Phone - I have no idea if they have fixed the reference issues but the are both alternatives to the TweetSharp nuget package. If you have issues with those packages you need to contact their authors or post issues in their repos.

3. Use a different library altogther, such as LinqToTwitter.

Good luck!

**Comment by roryprimrose** [comment]
Ah, thanks for the info. I hadn't read the readme. I've pulled in TweetMoaSharp to get going again. Thanks for working on this.

**Comment by Yortw** [comment]
No problem, hope the fork works for you :smile good luck!

**Comment by roryprimrose** [comment]
Yep, just deployed to production an hour ago. Perfect replacement to TweetSharp with no code changed, just package switch.

**Comment by Yortw** [comment]
:+1: Woah! Production? That's not a place I ever thought it would end up :wink:

**Comment by DaveGreasley** [comment]
Thanks for the heads up @Yortw! Apologies, I failed to read the readme too! 

I have replaced with TweetSharp-Unofficial. This also switched out without any code changes, although their nuget package has the same issue as this in that it ships with a version of Json.Net. I will have to give TweetMOASharp a go for next project.

**Comment by Yortw** [comment]
:+1: No probs! I can't say much about TweetSharp-Unofficial, I just happen to know it exists and includes at least some of the newer changes. TweetMoaSharp *should* be a drop in replacement, and *should* solve the dependency issue, but whatever works for you :smile:

**Comment by DaveGreasley** [comment]
Yeah, I'm now kind of wishing I'd gone with your package now as TweetSharp-Unofficial repo doesn't seem to have been updated in the last 2 years! Will try swapping in TweetMoaSharp tomorrow :)
